# Copyright OpenSearch Contributors
# SPDX-License-Identifier: Apache-2.0

name: Link Checker

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  linkchecker:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Load Excludes
      run: |
        LYCHEE_EXCLUDE=$(curl -fsSL https://raw.githubusercontent.com/opensearch-project/OpenSearch-Dashboards/HEAD/.lycheeexclude | grep -v '^#\|^$' | sed -e :a  -e 'N;s/\n/ --exclude /;ta')
        echo "LYCHEE_EXCLUDE=$LYCHEE_EXCLUDE" >> $GITHUB_ENV
    - name: Lychee Link Checker
      id: lychee
      uses: lycheeverse/lychee-action@v1.0.9
      with:
        # exclude urls that end with '$', which are regexes
        args: --accept=200,403,429 --exclude https://.+\$$ --exclude ${{ env.LYCHEE_EXCLUDE }} --exclude-mail "**/*.html" "**/*.md" "**/*.txt" "**/*.json" "**/*.js" "**/*.ts" "**/*.tsx"
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: Fail if there were link errors
      run: exit ${{ steps.lychee.outputs.exit_code }}
